apiVersion: api.example.com/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaler
    app.kubernetes.io/instance: scaler-sample
    app.kubernetes.io/part-of: scaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: scaler
  name: scaler-sample
spec:
  start: 19
  end: 21
  replicas: 4
  deployments:
    - name: nginx-deployment
      namespace: default