apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaler-controller-clusterrole
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scaler-controller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: scaler-controller-manager
  namespace: scaler-system  # Update with the correct namespace if different
roleRef:
  kind: ClusterRole
  name: scaler-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io